# Generated by Django 3.2.25 on 2024-05-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_event_fqptco', upload_to='images/')),
                ('event_date', models.DateField(blank=True)),
                ('category', models.CharField(choices=[('Health and Wellness', 'Health and Wellness'), ('Sport', 'Sport'), ('Music', 'Music'), ('Technology', 'Technology'), ('Family', 'Family'), ('Kids', 'Kids'), ('Food and Drink', 'Food and Drink'), ('Arts and Crafts', 'Arts and Crafts'), ('Education', 'Education')], default='Sport', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
